{% set name = "borb" %}
{% set version = "2.1.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/borb-{{ version }}.tar.gz
  sha256: 827b0fb2f721bdc5255b09a10c86b3b9cf3ff3765129cdbd54a8480c54a81651

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=51.1.1
  run:
    - cryptography >=37.0.4
    - fonttools >=4.22.1
    - lxml >=4.9.1
    # pillow 9.1.0 needed for qrcode 7.4.2
    - pillow >=9.1.0
    - python >=3.7
    - python-barcode >=0.13.1
    - qrcode >=6.1
    - requests >=2.24.0
    - setuptools >=51.1.1

    # Needed but not listed upstream
    - keyring

test:
  imports:
    - borb
    - borb.datastructure
    - borb.io
    - borb.pdf
    - borb.toolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jorisschellekens/borb
  summary: A library for reading, creating and manipulating PDF files in python.
  license: AGPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
