{% set name = "borb" %}
{% set version = "2.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/borb-{{ version }}.tar.gz
  sha256: 0f5a47140b3d36213d53941ff8749c3d831f46f48d1692304a6021a5d4892782

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=51.1.1
  run:
    - fonttools >=4.22.1
    - pillow >=7.1.0
    - python >=3.6
    - python-barcode >=0.13.1
    - qrcode >=6.1
    - requests >=2.24.0
    - setuptools >=51.1.1

test:
  imports:
    - borb
    - borb.datastructure
    - borb.io
    - borb.pdf
    - borb.toolkit
  commands:
    - pip check
  requires:
    - pip
    - lxml

about:
  home: https://github.com/jorisschellekens/borb
  summary: A library for reading, creating and manipulating PDF files in python.
  license: AGPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
