{% set name = "borb" %}
{% set version = "2.0.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/borb-{{ version }}.tar.gz
  sha256: e6c684ad4b81ad364bad0332bc4ba9209eb72ac10dedc283589169ba9cebdd5a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fonttools >=4.22.1
    - lxml
    - matplotlib-base
    - pillow >=7.1.0
    - python >=3.6
    - python-barcode >=0.13.1
    - qrcode >=6.1
    - requests >=2.24.0
    - setuptools ~=51.1.1

test:
  imports:
    - borb
    - borb.datastructure

about:
  home: https://github.com/jorisschellekens/borb
  summary: A library for reading, creating and manipulating PDF files in python.
  license: AGPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
