{% set name = "borb" %}
{% set version = "2.0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/borb-{{ version }}.tar.gz
  sha256: b2e2d910a7752fb39ed7687adc8f34d9b08220c892192557eaf2c0129c7141cb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fonttools
    - lxml
    - matplotlib-base
    - pillow >=7.1.0
    - python >=3.6
    - python-barcode >=0.13.1
    - qrcode >=6.1
    - requests >=2.24.0
    - setuptools

test:
  imports:
    - borb
    - borb.datastructure

about:
  home: https://github.com/jorisschellekens/borb
  summary: A library for reading, creating and manipulating PDF files in python.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
