{% set name = "borb" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/borb-{{ version }}.tar.gz
  sha256: 4232a8b506bf4a385b27780c39c833526fdc96999ed47d76ec409f75c3332379

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=51.1.1
  run:
    - python >={{ python_min }}
    - black
    - cryptography
    - fonttools
    - matplotlib-base
    - pillow
    - python-barcode
    - py-avataaars
    - requests
    - segno
    - setuptools >=51.1.1

test:
  imports:
    - borb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jorisschellekens/borb
  summary: A library for reading, creating and manipulating PDF files in python.
  license: AGPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
