schema_version: 1

context:
  name: borb
  version: "3.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/borb-${{ version }}.tar.gz
  sha256: 610a20720b5e2d0749d2867d1b18d82c69e9b140ac28552477a7dc3fac60b7a3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=51.1.1
  run:
    - python >=${{ python_min }}
    - black
    - cryptography
    - fonttools
    - matplotlib-base
    - pillow
    - python-barcode
    - py-avataaars
    - requests
    - segno
    - setuptools >=51.1.1

tests:
  - python:
      imports:
        - borb
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A library for reading, creating and manipulating PDF files in python.
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  homepage: https://github.com/jorisschellekens/borb

extra:
  recipe-maintainers:
    - thewchan
