schema_version: 1

context:
  name: borb
  version: "3.0.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/borb-${{ version }}.tar.gz
  sha256: 772ebd942ffae6f805fc267efd61f061029d73f51fc5bb82a76ca697bbd074a8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=51.1.1
  run:
    - python >=${{ python_min }}
    - setuptools >=51.1.1

tests:
  - python:
      imports:
        - borb
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A library for reading, creating and manipulating PDF files in python.
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  homepage: https://github.com/jorisschellekens/borb

extra:
  recipe-maintainers:
    - thewchan
