schema_version: 1

context:
  name: borb
  version: "3.0.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/borb-${{ version }}.tar.gz
  sha256: 504daba0a2f06262d83e28b790c5c2b26a73834a2f467cf637467ef2bbf5690b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=51.1.1
  run:
    - python >=${{ python_min }}
    - setuptools >=51.1.1

tests:
  - python:
      imports:
        - borb
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A library for reading, creating and manipulating PDF files in python.
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  homepage: https://github.com/jorisschellekens/borb

extra:
  recipe-maintainers:
    - thewchan
